# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(352, 352)
        widget.setMinimumSize(QtCore.QSize(352, 352))
        widget.setMaximumSize(QtCore.QSize(352, 352))
        self.progressBar = QtWidgets.QProgressBar(parent=widget)
        self.progressBar.setGeometry(QtCore.QRect(40, 320, 271, 23))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.file_path_label = QtWidgets.QLabel(parent=widget)
        self.file_path_label.setGeometry(QtCore.QRect(40, 280, 271, 31))
        self.file_path_label.setMaximumSize(QtCore.QSize(16777215, 48))
        self.file_path_label.setLineWidth(1)
        self.file_path_label.setWordWrap(True)
        self.file_path_label.setObjectName("file_path_label")
        self.title_text = QtWidgets.QLabel(parent=widget)
        self.title_text.setGeometry(QtCore.QRect(100, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_text.setFont(font)
        self.title_text.setObjectName("title_text")
        self.tabWidget = QtWidgets.QTabWidget(parent=widget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 60, 291, 211))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.select_button = QtWidgets.QPushButton(parent=self.tab_3)
        self.select_button.setGeometry(QtCore.QRect(20, 10, 251, 131))
        self.select_button.setObjectName("select_button")
        self.parse_button1 = QtWidgets.QPushButton(parent=self.tab_3)
        self.parse_button1.setGeometry(QtCore.QRect(100, 150, 101, 24))
        self.parse_button1.setObjectName("parse_button1")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.parse_button2 = QtWidgets.QPushButton(parent=self.tab_4)
        self.parse_button2.setGeometry(QtCore.QRect(100, 150, 101, 24))
        self.parse_button2.setObjectName("parse_button2")
        self.resume_text_edit = QtWidgets.QTextEdit(parent=self.tab_4)
        self.resume_text_edit.setGeometry(QtCore.QRect(20, 10, 251, 131))
        self.resume_text_edit.setObjectName("resume_text_edit")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(widget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "简历解析系统"))
        self.file_path_label.setText(_translate("widget", " "))
        self.title_text.setText(_translate("widget", "智能简历解析系统"))
        self.select_button.setText(_translate("widget", "点击上传文件"))
        self.parse_button1.setText(_translate("widget", "解析简历"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("widget", "文件上传"))
        self.parse_button2.setText(_translate("widget", "解析简历"))
        self.resume_text_edit.setPlaceholderText(_translate("widget", "请输入简历内容："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("widget", "手动输入"))
